// Generated by gencpp from file leap_hand/leap_positionResponse.msg
// DO NOT EDIT!


#ifndef LEAP_HAND_MESSAGE_LEAP_POSITIONRESPONSE_H
#define LEAP_HAND_MESSAGE_LEAP_POSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace leap_hand
{
template <class ContainerAllocator>
struct leap_positionResponse_
{
  typedef leap_positionResponse_<ContainerAllocator> Type;

  leap_positionResponse_()
    : position()  {
    }
  leap_positionResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::leap_hand::leap_positionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leap_hand::leap_positionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct leap_positionResponse_

typedef ::leap_hand::leap_positionResponse_<std::allocator<void> > leap_positionResponse;

typedef boost::shared_ptr< ::leap_hand::leap_positionResponse > leap_positionResponsePtr;
typedef boost::shared_ptr< ::leap_hand::leap_positionResponse const> leap_positionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leap_hand::leap_positionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leap_hand::leap_positionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::leap_hand::leap_positionResponse_<ContainerAllocator1> & lhs, const ::leap_hand::leap_positionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::leap_hand::leap_positionResponse_<ContainerAllocator1> & lhs, const ::leap_hand::leap_positionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace leap_hand

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leap_hand::leap_positionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_hand::leap_positionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_hand::leap_positionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50410efb3480c63b23b8b5fe2bea331a";
  }

  static const char* value(const ::leap_hand::leap_positionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50410efb3480c63bULL;
  static const uint64_t static_value2 = 0x23b8b5fe2bea331aULL;
};

template<class ContainerAllocator>
struct DataType< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leap_hand/leap_positionResponse";
  }

  static const char* value(const ::leap_hand::leap_positionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] position\n"
"\n"
;
  }

  static const char* value(const ::leap_hand::leap_positionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct leap_positionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leap_hand::leap_positionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leap_hand::leap_positionResponse_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEAP_HAND_MESSAGE_LEAP_POSITIONRESPONSE_H
