// Generated by gencpp from file leap_hand/leap_velocity.msg
// DO NOT EDIT!


#ifndef LEAP_HAND_MESSAGE_LEAP_VELOCITY_H
#define LEAP_HAND_MESSAGE_LEAP_VELOCITY_H

#include <ros/service_traits.h>


#include <leap_hand/leap_velocityRequest.h>
#include <leap_hand/leap_velocityResponse.h>


namespace leap_hand
{

struct leap_velocity
{

typedef leap_velocityRequest Request;
typedef leap_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct leap_velocity
} // namespace leap_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::leap_hand::leap_velocity > {
  static const char* value()
  {
    return "241a0480799a6297b297c9f6e498fe3c";
  }

  static const char* value(const ::leap_hand::leap_velocity&) { return value(); }
};

template<>
struct DataType< ::leap_hand::leap_velocity > {
  static const char* value()
  {
    return "leap_hand/leap_velocity";
  }

  static const char* value(const ::leap_hand::leap_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::leap_hand::leap_velocityRequest> should match
// service_traits::MD5Sum< ::leap_hand::leap_velocity >
template<>
struct MD5Sum< ::leap_hand::leap_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::leap_hand::leap_velocity >::value();
  }
  static const char* value(const ::leap_hand::leap_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::leap_hand::leap_velocityRequest> should match
// service_traits::DataType< ::leap_hand::leap_velocity >
template<>
struct DataType< ::leap_hand::leap_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::leap_hand::leap_velocity >::value();
  }
  static const char* value(const ::leap_hand::leap_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::leap_hand::leap_velocityResponse> should match
// service_traits::MD5Sum< ::leap_hand::leap_velocity >
template<>
struct MD5Sum< ::leap_hand::leap_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::leap_hand::leap_velocity >::value();
  }
  static const char* value(const ::leap_hand::leap_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::leap_hand::leap_velocityResponse> should match
// service_traits::DataType< ::leap_hand::leap_velocity >
template<>
struct DataType< ::leap_hand::leap_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::leap_hand::leap_velocity >::value();
  }
  static const char* value(const ::leap_hand::leap_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEAP_HAND_MESSAGE_LEAP_VELOCITY_H
