// Generated by gencpp from file leap_hand/leap_effort.msg
// DO NOT EDIT!


#ifndef LEAP_HAND_MESSAGE_LEAP_EFFORT_H
#define LEAP_HAND_MESSAGE_LEAP_EFFORT_H

#include <ros/service_traits.h>


#include <leap_hand/leap_effortRequest.h>
#include <leap_hand/leap_effortResponse.h>


namespace leap_hand
{

struct leap_effort
{

typedef leap_effortRequest Request;
typedef leap_effortResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct leap_effort
} // namespace leap_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::leap_hand::leap_effort > {
  static const char* value()
  {
    return "3a8f7ca4b38fbe820a7205cc08e38abf";
  }

  static const char* value(const ::leap_hand::leap_effort&) { return value(); }
};

template<>
struct DataType< ::leap_hand::leap_effort > {
  static const char* value()
  {
    return "leap_hand/leap_effort";
  }

  static const char* value(const ::leap_hand::leap_effort&) { return value(); }
};


// service_traits::MD5Sum< ::leap_hand::leap_effortRequest> should match
// service_traits::MD5Sum< ::leap_hand::leap_effort >
template<>
struct MD5Sum< ::leap_hand::leap_effortRequest>
{
  static const char* value()
  {
    return MD5Sum< ::leap_hand::leap_effort >::value();
  }
  static const char* value(const ::leap_hand::leap_effortRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::leap_hand::leap_effortRequest> should match
// service_traits::DataType< ::leap_hand::leap_effort >
template<>
struct DataType< ::leap_hand::leap_effortRequest>
{
  static const char* value()
  {
    return DataType< ::leap_hand::leap_effort >::value();
  }
  static const char* value(const ::leap_hand::leap_effortRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::leap_hand::leap_effortResponse> should match
// service_traits::MD5Sum< ::leap_hand::leap_effort >
template<>
struct MD5Sum< ::leap_hand::leap_effortResponse>
{
  static const char* value()
  {
    return MD5Sum< ::leap_hand::leap_effort >::value();
  }
  static const char* value(const ::leap_hand::leap_effortResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::leap_hand::leap_effortResponse> should match
// service_traits::DataType< ::leap_hand::leap_effort >
template<>
struct DataType< ::leap_hand::leap_effortResponse>
{
  static const char* value()
  {
    return DataType< ::leap_hand::leap_effort >::value();
  }
  static const char* value(const ::leap_hand::leap_effortResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEAP_HAND_MESSAGE_LEAP_EFFORT_H
