// Generated by gencpp from file leap_hand/leap_positionRequest.msg
// DO NOT EDIT!


#ifndef LEAP_HAND_MESSAGE_LEAP_POSITIONREQUEST_H
#define LEAP_HAND_MESSAGE_LEAP_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace leap_hand
{
template <class ContainerAllocator>
struct leap_positionRequest_
{
  typedef leap_positionRequest_<ContainerAllocator> Type;

  leap_positionRequest_()
    {
    }
  leap_positionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::leap_hand::leap_positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leap_hand::leap_positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct leap_positionRequest_

typedef ::leap_hand::leap_positionRequest_<std::allocator<void> > leap_positionRequest;

typedef boost::shared_ptr< ::leap_hand::leap_positionRequest > leap_positionRequestPtr;
typedef boost::shared_ptr< ::leap_hand::leap_positionRequest const> leap_positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leap_hand::leap_positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leap_hand::leap_positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace leap_hand

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leap_hand::leap_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_hand::leap_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_hand::leap_positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::leap_hand::leap_positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leap_hand/leap_positionRequest";
  }

  static const char* value(const ::leap_hand::leap_positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::leap_hand::leap_positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct leap_positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leap_hand::leap_positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::leap_hand::leap_positionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LEAP_HAND_MESSAGE_LEAP_POSITIONREQUEST_H
