// Generated by gencpp from file leap_hand/leap_velocityResponse.msg
// DO NOT EDIT!


#ifndef LEAP_HAND_MESSAGE_LEAP_VELOCITYRESPONSE_H
#define LEAP_HAND_MESSAGE_LEAP_VELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace leap_hand
{
template <class ContainerAllocator>
struct leap_velocityResponse_
{
  typedef leap_velocityResponse_<ContainerAllocator> Type;

  leap_velocityResponse_()
    : velocity()  {
    }
  leap_velocityResponse_(const ContainerAllocator& _alloc)
    : velocity(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::leap_hand::leap_velocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leap_hand::leap_velocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct leap_velocityResponse_

typedef ::leap_hand::leap_velocityResponse_<std::allocator<void> > leap_velocityResponse;

typedef boost::shared_ptr< ::leap_hand::leap_velocityResponse > leap_velocityResponsePtr;
typedef boost::shared_ptr< ::leap_hand::leap_velocityResponse const> leap_velocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leap_hand::leap_velocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::leap_hand::leap_velocityResponse_<ContainerAllocator1> & lhs, const ::leap_hand::leap_velocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::leap_hand::leap_velocityResponse_<ContainerAllocator1> & lhs, const ::leap_hand::leap_velocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace leap_hand

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leap_hand::leap_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_hand::leap_velocityResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_hand::leap_velocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "241a0480799a6297b297c9f6e498fe3c";
  }

  static const char* value(const ::leap_hand::leap_velocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x241a0480799a6297ULL;
  static const uint64_t static_value2 = 0xb297c9f6e498fe3cULL;
};

template<class ContainerAllocator>
struct DataType< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leap_hand/leap_velocityResponse";
  }

  static const char* value(const ::leap_hand::leap_velocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] velocity\n"
"\n"
;
  }

  static const char* value(const ::leap_hand::leap_velocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct leap_velocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leap_hand::leap_velocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leap_hand::leap_velocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEAP_HAND_MESSAGE_LEAP_VELOCITYRESPONSE_H
